dspace/config/dspace.cfg

The dspace.cfg reads the google.analytics.key property (to be set in the {dev,stage,prod}.properties file) for setting the {jspui,xmlui}.google.analytics.key properties. Enabled the xmlui.google.analytics.key property.
https://issues.umd.edu/browse/LIBCIR-21

LIBCIR-21. Google Analytics key property.

---

dspace-xmlui-mirage2/readme.md
dspace/modules/xmlui/pom.xml

Updated xmlui module to use mirage2.off instead of mireage2.on property.
https://issues.umd.edu/browse/LIBCIR-39

LIBCIR-39. Speedup MD-SOAR development cycle.

---

README.md
dspace/docs/LocalBuildInstructions.md
dspace/docs/Mirage2PrerequisitesOnServer.md
dspace/modules/xmlui-mirage2-communities/pom.xml
dspace/modules/xmlui-mirage2/pom.xml

Made Dmirage2.deps.included=false by default.
Updated documentation.
https://issues.umd.edu/browse/LIBCIR-48

LIBCIR-48. Investigate Mirage2 Prerequisite Installation procedure.

---

dspace/config/crosswalks/DIM2EZID.xsl
dspace/config/input-forms.xml

Made Title and Type required.
Updated Type dropdown's value pairs.
Updated EZID Type mapping in crosswalk.
https://issues.umd.edu/browse/LIBCIR-51

LIBCIR-51. Required Submission Fields.

---

dspace/modules/pom.xml
dspace/src/main/config/build.xml
pom.xml

Maven will only build solr on all-modules profile.
Ant solr index upgrade will not happen on "ant update"
https://issues.umd.edu/browse/LIBCIR-55

LIBCIR-55. Disable solr webapp module.

---

dspace/solr/search/conf/solrconfig.xml

Enabled extraction and solr-cell jars for the batch import indexing to work.
https://issues.umd.edu/browse/LIBCIR-65

LIBCIR-65. batch load succeeds, but items do not appear in collection.

---

dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/artifactbrowser/item-view.xsl

The sort ignores the mdschema for a field on the assumption that the user is going to be thinking in terms of the field name or qualifier.
https://issues.umd.edu/browse/LIBCIR-73

LIBCIR-73. Sort metadata fields in full item view by element and qualifier.

---

dspace/config/dspace.cfg

The PDF thumbnailer requires that ghostscript be installed on the server.
https://issues.umd.edu/browse/LIBCIR-71

LIBCIR-71. Enable the ImageMagick thumbnailer.

---

dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java

if any error occurs during a batch import, even the prior items in the batch that were loaded without error will not be commited due to transaction rollback.
This fix adds transaction commit after each item load.
https://issues.umd.edu/browse/LIBCIR-206

LIBCIR-206. Fix batch import issue.

---

dspace/modules/additions/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java

https://issues.umd.edu/browse/LIBCIR-235

LIBCIR-235. Log Datacite XML on HTTP 422 failure response.

---

dspace/modules/additions/src/main/java/org/dspace/identifier/DOIIdentifierProvider.java
dspace/modules/additions/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java

Notes:
- DataCite MDS API changes (Eventual Consistency for read) is affecting the DOI regsitration.
- Check for reserved status are returning false even though reservation has succeeded.
- We can skip reservation status check - if we just reserved and the request succeeded.
https://issues.umd.edu/browse/LIBCIR-241

LIBCIR-241. Skip checking DOI reservation in DataciteConnector.

---

dspace-xmlui-mirage2/src/main/webapp/scripts/search-controls.js
dspace/config/dspace.cfg
dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl

- Remove dcterms.creator from the Author browse index
- Update item view page Orcid link to use search filter instead of browse index.
- Fix javascript to display filters with selected value containing dot.
https://issues.umd.edu/browse/LIBCIR-263

LIBCIR-263. Orcid implementation changes.

---

dspace/bin/start-handle-server-fg

Added "dspace/bin/start-handle-server-fg" script, as it is needed by the "k8s-mdsoar" DSpace 7 configuration.
https://umd-dit.atlassian.net/browse/LIBCIR-288

LIBCIR-288. Added "start-handle-server-fg" script

---

dspace/src/main/docker/dspace-postgres-pgcrypto/Dockerfile

The latest Postgres 12 version, Postgres 12.15, appears to have some sort of issue with populating the database from downloaded sample data at startup.
Instead of processing the Postgres dump, the following is in the log:
```
server started
CREATE DATABASE
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mdsoar.sql
SET
SET
SET
SET
SET
set_config
------------
(1 row)
```
The existing steps work correctly with Postgres 12.14, so pinning to that version until a deeper investigation can be performed (or the problem simply corrects itself in the next version).
https://umd-dit.atlassian.net/browse/LIBCIR-312

LIBCIR-312. Pin Postgres version to 12.14

---

dspace/config/item-submission.xml
dspace/config/local.cfg.EXAMPLE
dspace/config/submission-forms.xml
dspace/docs/SubmissionForm.md

* Updated the submission form fields to match MD-SOAR DSpace 6 form submission, including field labels and hints. In MD-SOAR DSpace 6, where a hint referred to the “Add” button, changed to “Add more”, as that is the name of the link in DSpace 7.
* Modified the “Date of Issue” and “Publisher” fields to be in separate rows (and to take up the whole row) to match MD-SOAR DSpace 6, and to better accommodate the long hint on the “Date of Issue” field.
* Modified the “Type” (dc.type) hint to correspond better with the use of the drop-down list, and using the “Add more” link to add multiple entries.
* Modified the “dcterms.creator” (“Author ORCID(s)”) to validate the entry using the regular expression used in MD-SOAR DSpace 6 - `https:\/\/orcid.org\/\d{4}-\d{4}-\d{4}-\d{3}[X0-9]`
* Modified the …

LIBCIR-298. Modified submission form to closely match MD-SOAR DSpace 6

---

README-mdsoar.md
dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Modified the "dspace/config/local.cfg.EXAMPLE" file, adding the "usage-statistics.logBots" property from the "dspace/config/modules/usage-statistics.cfg" and setting it to "false" so that activity by spiders/bots will not be recorded by the Solr “statistics” core.
This implements the same setting that was in the DSpace 6 MD-SOAR.
Modified the "dspace/config/local.cfg.EXAMPLE" file, adding the "usage-statistics.authorization.admin.usage" property from the "dspace/config/modules/usage-statistics.cfg" and setting it to "true" so that the "Statistics" entry in the navbar is suppressed for non-admin users.
This was done to be consistent with the settings in the "umd-lib/k8s-mdsoar" repository
This implements the same setting that was in the DSpace 6 MD-SOAR.
Added …

LIBCIR-299. Disable logging crawler activity to solr statistics

---

dspace/config/emails/change_password
dspace/config/emails/doi_maintenance_error
dspace/config/emails/export_error
dspace/config/emails/export_success
dspace/config/emails/flowtask_notify
dspace/config/emails/harvesting_error
dspace/config/emails/internal_error
dspace/config/emails/register
dspace/config/emails/registration_notify
dspace/config/emails/submit_archive
dspace/config/emails/submit_reject
dspace/config/emails/submit_task
dspace/config/emails/subscriptions_content
dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Changed "DSpace" in email templates to "MD-SOAR".
Also adjusted properties in the "dspace/config/local.cfg.EXAMPLE" file used in email templates to match those in the Kubernetes production.
https://umd-dit.atlassian.net/browse/LIBCIR-300

LIBCIR-300. Replaced "DSpace" in email templates with "MD-SOAR".

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Set "webui.user.assumelogin" property to "true" to allow administrators to impersonate non-admins (as is allowed in DSpace 6).
Added documentation.
https://umd-dit.atlassian.net/browse/LIBCIR-315

LIBCIR-315. Enable administrators to impersonate non-admins

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Modified the "webui.browse.index" entries to match those in DSpace 6 MD-SOAR, including adding an additional entry to enable "Browse by Type".
Added information about the customization to the
"MdsoarCustomizations.md" file.
https://umd-dit.atlassian.net/browse/LIBCIR-314

LIBCIR-314. Modified configuration to include "Browse by Type"

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Added "eperson.subscription.onlynew", setting it to true, so that subscription emails are only sent out for new items (as opposed to both new and modified items).
Added property to "MdsoarCustomizations.md" and reorganized property list to be in alphabetical order.
https://umd-dit.atlassian.net/browse/LIBCIR-308

LIBCIR-308. Enabled "eperson.subscription.onlynew" property

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/DockerDevelopmentEnvironment.md
dspace/docs/MdsoarCustomizations.md

Added “Google Analytics Configuration” section to
“dspace/config/local.cfg.EXAMPLE”, leaving the "google.analytics.key" and "google.analytics.api-secret" properties blank because we probably don’t want analytics from the local development environment by default.
Added information about Google Analytics to the
“dspace/docs/MdsoarCustomizations.md” and
“dspace/docs/DockerDevelopmentEnvironment.md” documentation.
https://umd-dit.atlassian.net/browse/LIBCIR-304

LIBCIR-304. Added Google Analytics 4 configuration properties

---

dspace/modules/additions/src/main/java/org/dspace/browse/CrossLinks.java
dspace/modules/additions/src/test/java/org/dspace/browse/CrossLinksTest.java

Fixes an issue in the "CrossLinks" class to enable multiple "webui.browse.link" configuration entries with exact matches to different indexes to be processed properly.
This fixes a stock DSpace bug. The associated DSpace issue is
https://github.com/DSpace/DSpace/issues/8935
and a change similar to this one (except in the "dspace-api" module) was submitted in a pull request:
https://github.com/DSpace/DSpace/pull/8936
https://umd-dit.atlassian.net/browse/LIBCIR-326

LIBCIR-326. webui.browse.link CrossLinks: Fix for multiple exact matches

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md
dspace/docs/SimpleItemPage.md

Added configuration to "local.cfg.EXAMPLE" to configure "crosslinks" for the simple item page, so that specific fields will be hyperlinked to their appropriate "browse by" search page.
Added "SimpleItemPage.md" to record MD-SOAR customizations to the "simple item" page.
Updated "MdsoarCustomizations.md" to link to the "SimpleItemPage.md" and rearranged the links to be in alphabetical order.
https://umd-dit.atlassian.net/browse/LIBCIR-322

LIBCIR-322. Added CrossLinks configuration for MD-SOAR

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md
dspace/docs/SolrAutosuggest.md
dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/authority/SolrSuggestService.java
dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/authority/SuggestChoiceAuthority.java
dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/authority/SuggestService.java
dspace/modules/additions/src/main/resources/spring/spring-dspace-addon-umd-custom-services.xml
dspace/solr/search/conf/solrconfig.xml

Initial implementation of Solr autosuggest functionality for the "Format" and "Subject Keywords" submission form fields.
This implementation is based on the stock DSpace "ChoiceAuthority" plugin functionality.
https://umd-dit.atlassian.net/browse/LIBCIR-297

LIBCIR-297. Initial implementation of Solr autosuggest

---

dspace/docs/SimpleItemPage.md

Updated the "SimpleItemPage.md" documentation to record the "Links to Files" customization, which was missed in the original implementation.
https://umd-dit.atlassian.net/browse/LIBCIR-336

LIBCIR-336. Updated Simple Item page documentation for "Links to Files"

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Enabling the "org.dspace.content.Collection.findAuthorizedPerformanceOptimize" property significantly speeds up the display of the submission form for non-admins when selecting the “Submit item to MD-SOAR” link on the home page.
This property is not enabled by default (as outlined in https://github.com/DSpace/DSpace/issues/6033) because it is not compatible with Shibboleth or LDAP authentication and special groups. (see also the note for this property in "dspace/config/dspace.config".
Since MD-SOAR does not use Shibboeth or LDAP authentication, and has a large number of collection, it seems to meet the criteria for enabling this property.
https://umd-dit.atlassian.net/browse/LIBCIR-340

LIBCIR-340. Enable optimization for "select-collection-step" query

---

dspace/config/submission-forms.xml
dspace/docs/SubmissionForm.md

Modified configuration so that the "Text" entry is the first entry in the the "Type" drop-down on the submission form.
https://umd-dit.atlassian.net/browse/LIBCIR-348

LIBCIR-348. Make "Text" first entry in "Type" drop-down

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Only system admins should be able to permanently delete items, so
added properties to the "local.cfg.EXAMPLE" file to prevent community
and collection admins from permanently deleting items.
This also has the side effect of preventing community and collection
admins from moving items to a different collection.
Updated the documentation to describe this customization.
Also added "UMD Customization"/"End UMD Customization" markers
to all changes to the "local.cfg.EXAMPLE" file to simplify future DSpace
upgrades.
https://umd-dit.atlassian.net/browse/LIBCIR-347

LIBCIR-347. Disable item deletion for community and collection admins

---

dspace/config/local.cfg.EXAMPLE
dspace/docs/MdsoarCustomizations.md

Restores the stock DSpace behavior of allowing all users (including anonymous users) to view the usage statistics.
This reverses an incorrect configuration change made to MD-SOAR in LIBCIR-299, which restricted the usage statistics to admins.
Also removed the property from the list of customized properties in "dspace/docs/MdsoarCustomizations.md"
https://umd-dit.atlassian.net/browse/LIBCIR-352

LIBCIR-352. Enable all users to view usage statistics

---

dspace/config/spring/api/requestitem.xml
dspace/docs/DockerDevelopmentEnvironment.md

Followed the documentation instructions (see https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-ConfigureallrequeststogototheadministratorsofaCollection) and modified the “dspace/config/spring/api/requestitem.xml” file to use the “org.dspace.app.requestitem.CollectionAdministratorsRequestItemStrategy” strategy.
According to the documentation, this strategy will do the following:
* Send the request email to all the community administrators
* _If a community has no administrators, send an email to the help desk   email (if the “request.item.helpdesk.override” property is set to true_
**Note:** In our current configuration the “request.item.helpdesk.override” property is false, so this step is skipped.
* Send the request email to the item submitter
The email setup …

LIBCIR-360. Send request item emails to community admins

---

dspace/config/spring/api/requestitem.xml

Reverted the change to the “dspace/config/spring/api/requestitem.xml” file for LIBCIR-360, restoring to the stock DSpace usage of the “org.dspace.app.requestitem.RequestItemMetadataStrategy” strategy.
Kept the other documentation-related changes made in LIBCIR-360, because they were still correct.
https://umd-dit.atlassian.net/browse/LIBCIR-374

LIBCIR-374. Revert customization sending doc requests to collection admin

---

dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/ScopeResolver.java
dspace-server-webapp/src/test/java/org/dspace/app/opensearch/OpenSearchControllerIT.java

Fixes a NullPointerException when the "scope" parameter provided to the OpenSearch endpoint is a valid UUID, but is not a UUID associated with a Community or Collection.
Instead of throwing a NullPointerException, this change modifies the code to return a null scope (resulting in an "unscoped" OpenSearch request), as if the UUID were invalid, or otherwise not usable.
This fix was provided to DSpace as Pull Request #9482 - <https://github.com/DSpace/DSpace/pull/9482>. The customization markers added in this issue can be removed when MD-SOAR is updated to a DSpace version containing this change.
https://umd-dit.atlassian.net/browse/LIBCIR-386

LIBCIR-386. Fix OpenSearch NullPointerException for unknown valid UUIDs

---

dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java
dspace-api/src/main/java/org/dspace/storage/bitstore/DSBitStoreService.java

Modified the stock DSpace bitstore migration code to skip bitstreams that are not present in the assetstore.
While not needed for production, the ability to skip bitstreams is needed for the "sandbox", "test" and "qa" MD-SOAR migrations, as these instances have production database snapshots, but not all of the production bitstreams (the stock DSpace migration code fails with an error if any bitstream is missing).
The changes in this commit can be removed when the AWS S3 migration is complete.
https://umd-dit.atlassian.net/browse/LIBCIR-419

LIBCIR-419. Modify bitstore migration to skip missing files

---

dspace-api/src/main/java/org/dspace/checker/CheckerCommand.java
dspace-api/src/test/java/org/dspace/checker/ChecksumCheckerIT.java

Fixes the incremental storage of checksums for the "dspace checker" command by actually committing the changes to the database.
This change was provided to DSpace as DSpace Pull Request 10508.
Replacing "uncacheEntity" with "commit" as testing has shown that this is necessary to ensure that the checksums are properly updated when the checker is interrupted.
The provided integration test fails if checksums checked before the interruption are not properly recorded in the database. This class is slightly different from the version provided to DSpace for DSpace 9, due to changes in the use of the "java.util.Date" and "java.time.Instant" classes.
https://umd-dit.atlassian.net/browse/LIBCIR-430

LIBCIR-430. Fix checkpointing for "dspace checker" command
