dspace/config/xmlui.xconf
https://issues.umd.edu/browse/LIBCIR-3
=> LIBCIR-3. Enable the Mirage2 theme.

dspace/config/dspace.cfg
https://issues.umd.edu/browse/LIBCIR-3
=> LIBCIR-3. Make assetstore.dir locally configurable.

dspace/config/emails/bte_batch_import_error, dspace/config/emails/change_password, dspace/config/emails/doi_maintenance_error, dspace/config/emails/export_error, dspace/config/emails/export_success, dspace/config/emails/flowtask_notify, dspace/config/emails/harvesting_error, dspace/config/emails/internal_error, dspace/config/emails/register, dspace/config/emails/registration_notify, dspace/config/emails/submit_archive, dspace/config/emails/submit_reject, dspace/config/emails/submit_task, dspace/config/emails/subscription, dspace/config/emails/suggest
Updated all email templates to use:
- MD-SOAR instead of DSpace
- mdsoar-help@umd.edu instead of dspace-help@myu.edu
- no phone contact
https://issues.umd.edu/browse/LIBCIR-29
=> LIBCIR-29. custom email text needs to be set for password resets.

dspace/config/dspace.cfg
Changed "webui.user.assumelogin" to "true" to enable "Login as E-Person"
https://issues.umd.edu/browse/LIBCIR-32
=> LIBCIR-32. Enable "Login as E-Person" button

dspace/docs/LocalBuildInstructions.md, dspace/modules/pom.xml, pom.xml
Added other webapps depended by xmlui to default profile.
Added xmlui-plus profile
https://issues.umd.edu/browse/LIBCIR-39
=> LIBCIR-39. Speedup MD-SOAR development cycle.

README.md, dspace/docs/ThemeCustomization.md
https://issues.umd.edu/browse/LIBCIR-44
=> LIBCIR-44. Add documentation on community themes project.

build.properties, dspace/config/crosswalks/DIM2EZID.xsl, dspace/config/dspace.cfg, dspace/config/spring/api/identifier-service.xml
https://issues.umd.edu/browse/LIBCIR-11
=> LIBCIR-11. setup DOI assignment.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/FrostburgStateUniversity/styles/_style.scss, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/FrostburgStateUniversity/xsl/trail.xsl
Updated community logo location.
https://issues.umd.edu/browse/LIBCIR-38
=> LIBCIR-38. community theming.

build.properties, dspace/config/modules/discovery.cfg, dspace/config/modules/oai.cfg, dspace/config/modules/solr-statistics.cfg
Updated configuration to use external solr.
https://issues.umd.edu/browse/LIBCIR-12
=> LIBCIR-12. setup Solr cores.

dspace/config/dspace.cfg, dspace/config/modules/authentication-ip.cfg, dspace/config/modules/authentication.cfg
Enabled IP authentication and add IP group configuration.
https://issues.umd.edu/browse/LIBCIR-46
=> LIBCIR-46. Create new groups for campus IP ranges.

dspace/config/news-xmlui.xml
https://issues.umd.edu/browse/LIBCIR-57
=> LIBCIR-57. Replace Introductory Text on MD-SOAR Home Page.

dspace/config/spring/api/discovery.xml
https://issues.umd.edu/browse/LIBCIR-52
=> LIBCIR-52. Configure elements to include in browse/search indices.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/ScholarWorks@UMBC/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-61
=> LIBCIR-61. Text changes to UMBC footer.

dspace/config/dspace.cfg, dspace/config/spring/api/discovery.xml, dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
- Added new browse field "Type"
- Updated browse filed index configuration
- Added new custom search filters
https://issues.umd.edu/browse/LIBCIR-70
=> LIBCIR-70. browse/filter index configuration changes.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/FrostburgStateUniversity/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/GoucherCollege/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/LoyolaNotreDameLibrary/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/MarylandInstituteCollegeofArt/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/MorganStateUniversity/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/SalisburyUniversity/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/ScholarWorks@UMBC/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/StMarysCollege/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/TowsonUniversity/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/UniversityofBaltimore/xsl/footer.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/UniversityofMarylandBaltimore/xsl/footer.xsl, dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_global.scss
https://issues.umd.edu/browse/LIBCIR-62
=> LIBCIR-62. Add takedown request instructions to template footer.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/SalisburyUniversity/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-82
=> LIBCIR-82. Change email address in Salisbury template footer.

dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/artifactbrowser/item-view.xsl, dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
Added and modified fields to match the spec given in the issue.
https://issues.umd.edu/browse/LIBCIR-78
=> LIBCIR-78. Modify Simple Item Record Display.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/UniversityofBaltimore/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-84
=> LIBCIR-84. Updated University of Baltimore footer text.

dspace/config/modules/usage-statistics.cfg
Tested configuration and activated the usage statistics for everyone.
https://issues.umd.edu/browse/LIBCIR-67
=> LIBCIR-67. Enable SOLR Statistics in MD-SOAR

dspace/solr/statistics/conf/solrconfig.xml
Added url scheme confiugration for shard.
https://issues.umd.edu/browse/LIBCIR-67
=> LIBCIR-67. Enable SOLR Statistics in MD-SOAR.

dspace/config/input-forms.xml
https://issues.umd.edu/browse/LIBCIR-89
=> LIBCIR-89 Submission Form Modifications

dspace/config/input-forms.xml
https://issues.umd.edu/browse/LIBCIR-96
=> LIBCIR-96 Removing vocabulary link from subjects in item submission

dspace/config/input-forms.xml, dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-96
=> LIBCIR-96 Making additional textual changes to the submission form.

dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-96
=> LIBCIR-96 Putting periods on the Jr

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_global.scss
https://issues.umd.edu/browse/LIBCIR-100
=> LIBCIR-100. Corrected css to modify text size of next and previous only.

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_global.scss
https://issues.umd.edu/browse/LIBCIR-110
=> LIBCIR-110. Text wrapping issue in full item record

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
Create CC license link only if it is not empty.
=> LIBCIR-111. Enable Creative Commons License Option.

dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
Update overlay files with changes from upgrade.
https://issues.umd.edu/browse/LIBCIR-114
=> LIBCIR-114. Upgrade MD-SOAR to DSpace 5.5.

dspace/config/modules/usage-statistics.cfg
https://issues.umd.edu/browse/LIBCIR-117
=> LIBCIR-117. Disable logging crawler activity to solr statistics.

dspace/bin/import-setup.sh
https://issues.umd.edu/browse/LIBCIR-115
=> LIBCIR-115. Add import-setup.sh script to MD-SOAR.

dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-118
=> LIBCIR-118. Change label for License step in submission form.

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
Moved GTM script to immediately next to beginning of body tag.
https://issues.umd.edu/browse/LIBCIR-108
=> LIBCIR-108. Install Google Tag Manager GTM for MDSOAR.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/StMarysCollege/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-131
=> LIBCIR-131. Update footer information for St. Mary's.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/SalisburyUniversity/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-132
=> LIBCIR-132. changed the address in footer of Salisbury University

dspace/config/news-xmlui.xml
https://issues.umd.edu/browse/LIBCIR-136
=> LIBCIR-136. Added links to home page.

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
https://issues.umd.edu/browse/LIBCIR-145
=> LIBCIR-145. Added submission link logged in user dropdown option.

dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-137
=> LIBCIR-137: Changed the 'communities' to 'institution' in header.

dspace/config/news-xmlui.xml
https://issues.umd.edu/browse/LIBCIR-136
=> LIBCIR-136: Static link modified to relative links on home page.

dspace/config/input-forms.xml
https://issues.umd.edu/browse/LIBCIR-146
=> LIBCIR-146: Modified the hint text in Submission form.

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_global.scss, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/EditProfile.java, dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-149
=> Feature/libcir 149: Added the hint text for required elements on registration page. 

dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-150
=> LIBCIR-150: Thumbnail note is added to file upload section.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/UniversityofBaltimore/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-160
=> LIBCIR-160: Replaced old email with new one.

dspace-api/pom.xml, dspace-jspui/pom.xml, dspace-lni/dspace-lni-client/pom.xml, dspace-lni/pom.xml, dspace-oai/pom.xml, dspace-rdf/pom.xml, dspace-rest/pom.xml, dspace-services/pom.xml, dspace-solr/pom.xml, dspace-sword/pom.xml, dspace-swordv2/pom.xml, dspace-xmlui-mirage2/pom.xml, dspace-xmlui/pom.xml, dspace/modules/additions/pom.xml, dspace/modules/jspui/pom.xml, dspace/modules/lni/pom.xml, dspace/modules/oai/pom.xml, dspace/modules/pom.xml, dspace/modules/rdf/pom.xml, dspace/modules/rest/pom.xml, dspace/modules/solr/pom.xml, dspace/modules/sword/pom.xml, dspace/modules/swordv2/pom.xml, dspace/modules/xmlui-mirage2-communities/pom.xml, dspace/modules/xmlui-mirage2/pom.xml, dspace/modules/xmlui/pom.xml, dspace/pom.xml, pom.xml
https://issues.umd.edu/browse/LIBCIR-172
=> Bumped version to 5.7-mdsoar-0

dspace-xmlui-mirage2/src/main/webapp/scripts.xml, dspace-xmlui-mirage2/src/main/webapp/scripts/autocomplete.js, dspace-xmlui-mirage2/src/main/webapp/scripts/jquery-3.2.1.js, dspace-xmlui-mirage2/src/main/webapp/scripts/jquery-ui.js, dspace-xmlui-mirage2/src/main/webapp/styles/_style.scss, dspace/config/dspace.cfg, dspace/modules/additions/src/main/java/org/dspace/discovery/SearchService.java, dspace/modules/additions/src/main/java/org/dspace/discovery/SolrServiceImpl.java, dspace/modules/xmlui-mirage2-communities/pom.xml, dspace/modules/xmlui-mirage2/pom.xml, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/discovery/json/JSONDiscoverySuggester.java, dspace/modules/xmlui/src/main/webapp/aspects/json-solr.xmap, dspace/solr/search/conf/solrconfig.xml
https://issues.umd.edu/browse/LIBCIR-147
=> Feature/libcir 147: Remove repeating terms from suggestion list. 

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/HoodCollege/xsl/trail.xsl
https://issues.umd.edu/browse/LIBCIR-186
=> LIBCIR-186: Hood College breadcrumb navigation change.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/HoodCollege/xsl/trail.xsl, dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/StevensonUniversity/xsl/trail.xsl
https://issues.umd.edu/browse/LIBCIR-185
=> LIBCIR-185: Stevenson University breadcrumb navigation update.

dspace/modules/additions/src/main/java/org/dspace/discovery/SolrServiceImpl.java
Copying changes from https://github.com/DSpace/DSpace/pull/2045
https://issues.umd.edu/browse/LIBCIR-205
=> LIBCIR-205. Change Solr Implementation to use HTTP POST.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/UniversityofBaltimore/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-214
=> LIBCIR-214. Update University of Baltimore contact information.

dspace-xmlui-mirage2/src/main/webapp/.bowerrc, dspace/src/main/assembly/dspace-installer-distribution.xml
https://issues.umd.edu/browse/LIBCIR-212
=> LIBCIR-212. Package dspace-install as distribution tarball to server

README.md, dspace/pom.xml
Missed to include the pom.xml and README.md changes in the last commit.
https://issues.umd.edu/browse/LIBCIR-212
=> LIBCIR-212. Package dspace-install as distribution tarball to server..

dspace/modules/xmlui-mirage2-communities/pom.xml, dspace/modules/xmlui-mirage2/pom.xml
https://issues.umd.edu/browse/LIBCIR-220
=> LIBCIR-220. Odd characters in breadcrumb trail.

dspace/modules/xmlui-mirage2-communities/src/main/webapp/themes/FrostburgStateUniversity/xsl/footer.xsl
https://issues.umd.edu/browse/LIBCIR-251
=> LIBCIR-251. Update to Frostburg community footer.

dspace/config/news-xmlui.xml
https://issues.umd.edu/browse/LIBCIR-262
=> LIBCIR-262. Remove MICA from institution list

Dockerfile.ant, Dockerfile.dependencies, Dockerfile.dev, Dockerfile.tomcat, README.md, docker-compose.yml, dspace/config/input-forms.xml, dspace/config/spring/api/discovery.xml, dspace/modules/additions/src/main/java/org/dspace/submit/step/DescribeStep.java, dspace/modules/pom.xml, dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl, dspace/modules/xmlui-mirage2/src/main/webapp/xsl/core/attribute-handlers.xsl, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Params.java, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Text.java, dspace/modules/xmlui/src/main/resources/aspects/Discovery/i18n/messages.xml, dspace/modules/xmlui/src/main/webapp/i18n/messages.xml, dspace/src/main/docker-compose/local.cfg
- Add Custom ORCID input field type.
- Implement ORCID field display with validation.
- Display ORCID values separately in item view
https://issues.umd.edu/browse/LIBCIR-263
=> LIBCIR-263. ORCID Implementation.

dspace/config/input-forms.xml, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java, dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBCIR-264
=> LIBCIR-264. Updated submission form.

dspace/config/input-forms.xml, dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/scripts.xml, dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/scripts/admin-orcid-validation.js, dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/elements.xsl, dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/administrative/item/EditItemMetadataForm.java
https://issues.umd.edu/browse/LIBCIR-267
=> LIBCIR-267. Fix submission form and ORCID validation issues.

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
https://issues.umd.edu/browse/LIBCIR-268
=> LIBCIR-268. 'Author/Creator ORCID' should only display dcterms.creator.

.vscode/launch.json
Copied ".vscode/launch.json" file from "umd-lib/dspace" repository to support VS Code debugging as described in
"dspace/docs/DockerDevelopmentEnvironment.md"
https://umd-dit.atlassian.net/browse/LIBCIR-324
=> LIBCIR-324. Added ".vscode/launch.json" to support VS Code debugging

dspace/config/local.cfg.EXAMPLE, dspace/docs/SubmissionForm.md
Modified the submission form configuration to allow submission without uploading a file, in accordance with MD-SOAR submission policy.
https://umd-dit.atlassian.net/browse/LIBCIR-342
=> LIBCIR-342. File uploads should be optional.

dspace/config/spring/api/identifier-service.xml, dspace/docs/DataCiteDOI.md
https://umd-dit.atlassian.net/browse/LIBCIR-375
=> LIBCIR-375. Disable doi-filter.
